Test

diff --git a/.github/workflows/back-dockerPush.yml b/.github/workflows/back-dockerPush.yml
--- a/.github/workflows/back-dockerPush.yml
+++ b/.github/workflows/back-dockerPush.yml
@@ -55,25 +55,16 @@ jobs:
         id: data
         run: |
           awk 'NR>5' /tmp/coverage0.txt > /tmp/coverage1.txt
-          echo "embeds=[{\"type\":\"rich\",\"title\":\"$(grep -q "0 failed" /tmp/results.txt && echo "✅ All test are checked" || echo "❌ Errors with the test")\",\"description\":\"**Test back result:**\n$(tail -n 5 /tmp/results.txt  | tr '\n' "&" | sed 's/&/\\n/g')\n**Coverage :**\",\"color\":$(grep -q "0 failed" /tmp/results.txt && echo 38912 || echo 16525609),\"fields\":[{\"name\":\"**Stmts**\",\"value\":\"$(grep 'All files' /tmp/coverage0.txt | cut -d '|' -f 2 | tr -d ' ')%\",\"inline\":true},{\"name\":\"**Branches**\",\"value\":\"$(grep 'All files' /tmp/coverage0.txt | cut -d '|' -f 3 | tr -d ' ')%\",\"inline\":true},{\"name\":\"**Functions**\",\"value\":\"$(grep 'All files' /tmp/coverage0.txt | cut -d '|' -f 4 | tr -d ' ')%\",\"inline\":true},{\"name\":\"**Lines**\",\"value\":\"$(grep 'All files' /tmp/coverage0.txt | cut -d '|' -f 5 | tr -d ' ')%\",\"inline\":true}]}]" >> "$GITHUB_OUTPUT"
+          echo "embeds=[{\"type\":\"rich\",\"title\":\"$(grep -q "failed" /tmp/results.txt && echo "❌ Errors with the test" || echo "✅ All test are checked")\",\"description\":\"**Test back result:**\n$(tail -n 5 /tmp/results.txt  | tr '\n' "&" | sed 's/&/\\n/g')\n**Coverage :**\",\"color\":$(grep -q "failed" /tmp/results.txt && echo 16525609 || echo 38912),\"fields\":[{\"name\":\"**Stmts**\",\"value\":\"$(grep 'All files' /tmp/coverage0.txt | cut -d '|' -f 2 | tr -d ' ')%\",\"inline\":true},{\"name\":\"**Branches**\",\"value\":\"$(grep 'All files' /tmp/coverage0.txt | cut -d '|' -f 3 | tr -d ' ')%\",\"inline\":true},{\"name\":\"**Functions**\",\"value\":\"$(grep 'All files' /tmp/coverage0.txt | cut -d '|' -f 4 | tr -d ' ')%\",\"inline\":true},{\"name\":\"**Lines**\",\"value\":\"$(grep 'All files' /tmp/coverage0.txt | cut -d '|' -f 5 | tr -d ' ')%\",\"inline\":true}]}]" >> "$GITHUB_OUTPUT"
         # Green color 38912
 
       - name: ERROR Send coverage to discord
         uses: Ilshidur/action-discord@master
-        if: steps.tests.outcome == 'failure'
         env:
           DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
           DISCORD_USERNAME: GitHub
           DISCORD_AVATAR: https://cdn.discordapp.com/avatars/1138225091528904714/df91181b3f1cf0ef1592fbe18e0962d7.webp?size=100
           DISCORD_EMBEDS: ${{ steps.data.outputs.embeds }}
-
-      - name: SUCCESS Send coverage to discord
-        uses: Ilshidur/action-discord@master
-        if: steps.tests.outcome == 'success'
-        env:
-          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
-        with:
-          args: "✅ All test are checked"
 
       - name: Echo errors
         if: steps.tests.outcome == 'failure'
