Test

diff --git a/.github/workflows/back-dockerPush.yml b/.github/workflows/back-dockerPush.yml
--- a/.github/workflows/back-dockerPush.yml
+++ b/.github/workflows/back-dockerPush.yml
@@ -55,7 +55,7 @@ jobs:
         id: data
         run: |
           awk 'NR>5' /tmp/coverage0.txt > /tmp/coverage1.txt
-          echo "embeds=[{\"type\":\"rich\",\"title\":\"❌ Errors with the test\",\"description\":\"**Test back result:**\n$(tail -n 5 /tmp/results.txt  | tr '\n' "&" | sed 's/&/\\n/g')\n**Coverage :**\",\"color\":16711680,\"fields\":[{\"name\":\"**Stmts**\",\"value\":\"$(grep 'All files' /tmp/coverage0.txt | cut -d '|' -f 2 | tr -d ' ')%\",\"inline\":true},{\"name\":\"**Branches**\",\"value\":\"$(grep 'All files' /tmp/coverage0.txt | cut -d '|' -f 3 | tr -d ' ')%\",\"inline\":true},{\"name\":\"**Functions**\",\"value\":\"$(grep 'All files' /tmp/coverage0.txt | cut -d '|' -f 4 | tr -d ' ')%\",\"inline\":true},{\"name\":\"**Lines**\",\"value\":\"$(grep 'All files' /tmp/coverage0.txt | cut -d '|' -f 5 | tr -d ' ')%\",\"inline\":true}]}]" >> "$GITHUB_OUTPUT"
+          echo "embeds=[{\"type\":\"rich\",\"title\":\"$(grep -q "0 failed" /tmp/results.txt && echo "✅ All test are checked" || echo "❌ Errors with the test")\",\"description\":\"**Test back result:**\n$(tail -n 5 /tmp/results.txt  | tr '\n' "&" | sed 's/&/\\n/g')\n**Coverage :**\",\"color\":$(grep -q "0 failed" /tmp/results.txt && echo 38912 || echo 16525609),\"fields\":[{\"name\":\"**Stmts**\",\"value\":\"$(grep 'All files' /tmp/coverage0.txt | cut -d '|' -f 2 | tr -d ' ')%\",\"inline\":true},{\"name\":\"**Branches**\",\"value\":\"$(grep 'All files' /tmp/coverage0.txt | cut -d '|' -f 3 | tr -d ' ')%\",\"inline\":true},{\"name\":\"**Functions**\",\"value\":\"$(grep 'All files' /tmp/coverage0.txt | cut -d '|' -f 4 | tr -d ' ')%\",\"inline\":true},{\"name\":\"**Lines**\",\"value\":\"$(grep 'All files' /tmp/coverage0.txt | cut -d '|' -f 5 | tr -d ' ')%\",\"inline\":true}]}]" >> "$GITHUB_OUTPUT"
         # Green color 38912
 
       - name: ERROR Send coverage to discord
