Improve github actions for discord

diff --git a/.github/workflows/client_discord-dockerPush.yml b/.github/workflows/client_discord-dockerPush.yml
--- a/.github/workflows/client_discord-dockerPush.yml
+++ b/.github/workflows/client_discord-dockerPush.yml
@@ -42,12 +42,46 @@ jobs:
       - name: Check out repository code
         uses: actions/checkout@v3
       - name: Install dependencies
+        working-directory: ./clientDiscord
         run: |
-          cd clientDiscord/ && npm install
-      - name: Create summary
+          npm install
+      - name: Run tests and create summary
+        id: tests
+        continue-on-error: true
+        working-directory: ./clientDiscord
         run: |
-          cd clientDiscord/ && export NODE_OPTIONS=--no-experimental-fetch && npm test 2>> /tmp/results.txt >> /tmp/coverage0.txt
-          awk 'NR>5' /tmp/coverage0.txt > /tmp/coverage1.txt && sed '$ d' /tmp/coverage1.txt > $GITHUB_STEP_SUMMARY && echo -e "" >> $GITHUB_STEP_SUMMARY && cat /tmp/results.txt >> $GITHUB_STEP_SUMMARY
+          export NODE_OPTIONS=--no-experimental-fetch && npm test 2>> /tmp/results.txt >> /tmp/coverage0.txt
+      - name: Prepare data
+        id: data
+        run: |
+          awk 'NR>5' /tmp/coverage0.txt > /tmp/coverage1.txt
+          echo "embeds=[{\"type\":\"rich\",\"title\":\"$(grep -q "failed" /tmp/results.txt && echo "❌ Errors with the test [CLIENT_DISCORD]" || echo "✅ All test are checked [CLIENT_DISCORD]")\",\"description\":\"**Test client discord result:**\n$(tail -n 5 /tmp/results.txt  | tr '\n' "&" | sed 's/&/\\n/g')\n**Coverage :**\",\"color\":$(grep -q "failed" /tmp/results.txt && echo 16525609 || echo 38912),\"fields\":[{\"name\":\"**Statements**\",\"value\":\"$(grep 'All files' /tmp/coverage0.txt | cut -d '|' -f 2 | tr -d ' ')%\",\"inline\":true},{\"name\":\"**Branches**\",\"value\":\"$(grep 'All files' /tmp/coverage0.txt | cut -d '|' -f 3 | tr -d ' ')%\",\"inline\":true},{\"name\":\"**Functions**\",\"value\":\"$(grep 'All files' /tmp/coverage0.txt | cut -d '|' -f 4 | tr -d ' ')%\",\"inline\":true},{\"name\":\"**Lines**\",\"value\":\"$(grep 'All files' /tmp/coverage0.txt | cut -d '|' -f 5 | tr -d ' ')%\",\"inline\":true}]}]" >> "$GITHUB_OUTPUT"
+
+      - name: ERROR Send coverage to discord
+        uses: Ilshidur/action-discord@master
+        env:
+          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
+          DISCORD_USERNAME: GitHub
+          DISCORD_AVATAR: https://cdn.discordapp.com/avatars/1138225091528904714/df91181b3f1cf0ef1592fbe18e0962d7.webp?size=100
+          DISCORD_EMBEDS: ${{ steps.data.outputs.embeds }}
+
+      - name: Echo errors
+        if: steps.tests.outcome == 'failure'
+        run: |
+          sed '$ d' /tmp/coverage1.txt > $GITHUB_STEP_SUMMARY
+          echo -e "\n" >> $GITHUB_STEP_SUMMARY
+          cat /tmp/results.txt >> $GITHUB_STEP_SUMMARY
+          echo -e "\n" >> $GITHUB_STEP_SUMMARY
+          echo "❌ Errors with the test" >> $GITHUB_STEP_SUMMARY
+          exit 1
+      - name: Echo success
+        if: steps.tests.outcome == 'success'
+        run: |
+          echo -e "\n" >> $GITHUB_STEP_SUMMARY
+          sed '$ d' /tmp/coverage1.txt > $GITHUB_STEP_SUMMARY
+          cat /tmp/results.txt >> $GITHUB_STEP_SUMMARY
+          echo -e "\n" >> $GITHUB_STEP_SUMMARY
+          echo "✅ All test are checked" >> $GITHUB_STEP_SUMMARY
 
   Build_Push:
     runs-on: ubuntu-latest
